### ISSUE TITLE
Reliability of Windows 8 Tiles

### ISSUE THREAD

**Issue by jacksonj04** [RealFaviconGenerator/realfavicongenerator#21] opened 2014-02-07 10:10 UTC
I've just used the icon generator, and for the most part it's worked exactly as intended. However, for W8 tiles it seems to be a bit quirky. For three different sites I've seen the following:
- Everything works exactly as expected, all tile sizes are available, validator passes.
- The only available tile sizes are small and medium (not wide or large), validator passes.
- The only available tile sizes are small and medium (not wide or large), and validator fails on some of the W8 image sizes.

Any ideas, or other people experiencing this one?

**Comment by phbernard** [comment] 2014-02-07 22:00
Strange. The size of the master picture can explain the absence of some generated pictures. The master picture is supposed to be at least 260x260. However, RFG accepts smaller pics, down to 70x70. In that case, the larger generated pictures are missing and the HTML code is generated accordingly.

However, I have no explanation for the checker results, which differ in your points 2 and 3. When some pictures are missing, it is supposed to raise a warning. In other words, if you submit a picture smaller than 260x260, you won't have a "full green" report.

Could you mail me (philippe@realfavicongenerator.net) your master pictures so I can try to reproduce the issue?

**Comment by phbernard** [comment] 2014-02-21 14:08
I need some feedback to work on this issue. If I don't receive any in the next few days, I will consider that my "too small master picture" hypothesis is good-enough and I will close the ticket.

**Comment by phbernard** [comment] 2014-02-26 15:25
Sorry, I can't do anything without additional feedback. I close the issue for cleanup.

**Closed as completed** 2014-02-26 15:25 UTC
Labels: bug, invalid

**Comment by JHGrove3** [comment] 2014-03-13 19:46
For what it's worth, we had to delete the two lines for the Windows tiles, because they appeared to crash our Mura 6.1 CMS.

Without those two lines the favicons work fine.  But with them the page would render a cold fusion error.

**Comment by phbernard** [comment] 2014-03-14 10:33
A crash? Wow! Not good. You must be talking about these two lines:

```
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-TileImage" content="/mstile-144x144.png">
```

I don't know anything at all about ColdFusion and I couldn't find relevant information about such issue. Such crash means that ColdFusion processes these markups in a way or another (while server's code usually ignore HTML code and sends it as is to the client). Do you have a clue of what can happen? A kind of "markup filter" somewhere? A feature that dynamically verifies the HTML?
