### ISSUE TITLE
Error on HTML Validation

### ISSUE THREAD

**Issue by ghost** [RealFaviconGenerator/realfavicongenerator#294] opened 2016-11-15 12:03 UTC
Theres an Error with one ouf youf Favicons

![faviconerror](https://cloud.githubusercontent.com/assets/23476962/20305059/d9caf512-ab33-11e6-9da7-b643a25211a3.JPG)

**Comment by KIPdeKIP** [comment] 2016-11-15 14:37
#239

**Comment by phbernard** [comment] 2016-11-16 09:18
As @KIPdeKIP suggests, this issue is a duplicate of #239 . However, it is interesting because of its title, making it easier to find a clue for people who wonder why the hell a validation error can happen. So thank you :)

**Closed as completed by phbernard** 2016-11-16 09:18 UTC
Labels: duplicate
