### ISSUE TITLE
Desktop icons not generating

### ISSUE THREAD

**Issue by devilmark84** [RealFaviconGenerator/realfavicongenerator#458] opened 2021-02-01 11:25 UTC
Hi all!
I'm using the Node-CLI version of this awesome service but when I declare in `faviconDescription.json`:
```json
{
  "desktopBrowser": {
    "design": "background",
    "backgroundColor": "#ffffff",
    "backgroundRadius": 0.45,
    "imageScale": 0.8
  }
}
```
The system ignores the backgroundRadius value generating the images without rounding corners.
Can you please fix this?

Thanks in advance

**Comment by craighutch** [comment] 2021-02-02 03:44
Duplicate of #449

**Closed as completed** 2021-03-31 07:45 UTC
