### ISSUE TITLE
JSON file error.

### ISSUE THREAD

**Issue by woohoogle** [RealFaviconGenerator/realfavicongenerator#79] opened 2014-09-07 21:49 UTC
Hi I'm receiving this error in wordpress when trying to activate my Favicon. I have no idea what it means. Can you help at all please?

An error occured: Cannot download JSON file at http://realfavicongenerator.net/files/8bafa17205e30f0b725c4dbf339a07dfcb4c6202/json_result.json: name lookup timed out

Many thanks, Matt

**Comment by phbernard** [comment] 2014-09-07 21:54
Hi,

I clicked the link and I was able to download the corresponding JSON file, which looks fine. The error message you get looks like a DNS error. An internet connection issue, maybe?

**Comment by woohoogle** [comment] 2014-09-07 22:19
Hi and thanks for your quick response! I can also download the JSON file by visiting the link. It downloads and opens just fine. The error message is slightly different in Firefox (below) from Chrome (above):

An error occured: Cannot download JSON file at http://realfavicongenerator.net/files/a72d8ccb5db7999e56fd22cf5c26f0c45084d420/json_result.json: Couldn't resolve host 'realfavicongenerator.net'

I also have no problem accessing 'realfavicongenerator.net' from the same browser where I see the message. Any other ideas what this could be at all?

**Comment by phbernard** [comment] 2014-09-07 22:24
Hum... either there is something wrong with the realfavicongenerator.net domain name (unlikely but...) or that's your Internet connection. Could you try to visit a Web site you never went before? (to force a DNS request)

**Comment by woohoogle** [comment] 2014-09-07 22:32
I just invented a name, somethingawesome.com - typed it in and went straight to some guy's blog.
Tried the process again, but still getting the error message.. Hmn, frustrating these favicons, eh? ;)

**Comment by phbernard** [comment] 2014-09-07 22:35
Ouch! OK so the issue is really the domain name... I'm a bit clueless here, I'll try to investigate this tomorrow.

**Comment by woohoogle** [comment] 2014-09-07 22:36
Many thanks, I've implemented a temporary solution for now (an older and much less impressive plugin!), but please do let me know if you get anywhere with the issue so I can switch things up. Cheers!

**Comment by phbernard** [comment] 2014-09-09 09:27
Well, I'm a bit clueless. Yet, I realize something: this is your WordPress server which complains about the JSON download error, not your own station (by the way, you were able to edit your favicon by being redirected to http://realfavicongenerator.net/). Are you aware of any server side restrictions? What is your hosting solution?

**Comment by panfanky** [comment] 2021-11-01 08:52
This problem happens again. Even tried switching off https on my side, no good, it still asks for secured JSON, which is probably secured wrongly.
Cannot download JSON file at https://realfavicongenerator.net/files/e2a9386a78ebfd647d382770a076b7badeca532a/json_result.json: cURL error 60: SSL certificate problem: certificate has expired

**Comment by phbernard** [comment] 2021-11-04 13:46
Hi @panfanky, apparently the issue you face is #470.

I close this one, which is pretty old.

**Closed as completed by phbernard** 2021-11-04 13:46 UTC

**Comment by StudentCyberOps** [comment] 2024-10-26 16:38
[-] Failed to download the JSON index file. Check your internet connection.

2024 and i can't download anything :( help

**Comment by phbernard** [comment] 2024-11-09 19:17
Could you help me reproduce the issue? What happened?
