### ISSUE TITLE
og:image content URL doesn't carry over to code snippet

### ISSUE THREAD

**Issue by edelstone** [RealFaviconGenerator/realfavicongenerator#373] opened 2018-03-27 08:24 UTC
The Facebook meta generator has a field for _URL of the directory where the Facebook Open Graph image will be stored_ but if you put a URL in here it doesn't actually end up in the `<head>` code snippet on the next page.

Seems to always just be `<meta property="og:image" content="/og-image.jpg">` no matter what you put in there.

<img width="423" alt="screen shot 2018-03-27 at 3 25 41 am" src="https://user-images.githubusercontent.com/8269046/37955559-8d6edacc-316e-11e8-976b-b8151b6028bd.png">

**Comment by phbernard** [comment] 2018-03-27 11:22
I can't reproduce the issue:

![image](https://user-images.githubusercontent.com/423852/37964352-759bb340-31c1-11e8-8731-d829a36df28a.png)

However, that might be due to a caching issue. I've just made sure the js would reload. Could you give it another try?

**Comment by edelstone** [comment] 2018-03-27 12:13
Yeah it's still happening for me. Here is a demo.

http://recordit.co/3Vb0ttYm31

I'm using Chrome for Mac (Version 65.0.3325.181 (Official Build) (64-bit))

**Comment by phbernard** [comment] 2018-03-27 15:01
Damn! That was a caching issue indeed, just not the one I though :-/

It should be fixed now.

**Comment by edelstone** [comment] 2018-03-27 18:03
Shall I test again?

**Comment by edelstone** [comment] 2018-03-27 18:06
Upon testing from my end, the problem I was experiencing is fixed.

Thanks!!

**Comment by phbernard** [comment] 2018-03-29 09:19
Great! Thank you @edelstone

**Closed as completed by phbernard** 2018-03-29 09:19 UTC
Labels: bug
