### ISSUE TITLE
Apply color profile to scaled images

### ISSUE THREAD

**Issue by dwaite** [RealFaviconGenerator/realfavicongenerator#20] opened 2014-02-06 21:30 UTC
Converting a logo, I see some versions which kept the sRGB profile and some which dropped it. This resulted in some red icons, and some which had turned somewhat pink.

The files which did not keep the profile are:
mstile-144x144.png
favicon-_x_.png
apple-touch-icon.png
apple-touch-icon-_x_.png

**Comment by phbernard** [comment] 2014-02-06 21:40
Hum... not good. I suppose you used the "Compression" option? Could you send me your master picture at philippe@realfavicongenerator.net to reproduce the issue? Could you also tell me the platform and software you use to display the picture?

**Comment by phbernard** [comment] 2014-02-21 14:09
I really would like to reproduce this issue, could you send me your picture?

**Comment by aventrix** [comment] 2014-03-11 14:49
I don't know the cause, but I noticed some color changes in my compressed vs uncompressed versions as well. When viewing the compressed versions through Preview in Mac OSX Lion, the color is lightened, but viewing the compressed versions in firefox or chrome does not distort the color. I'm attaching some files (master, compressed, uncompressed) - not sure if it will show up here. I can email them to you if this doesn't work.

apple-touch-icon-144x144 (compressed):
![apple-touch-icon-144x144-compressed](https://f.cloud.github.com/assets/5693147/2386429/00e5b1ee-a92c-11e3-84aa-fe759476652a.png)

apple-touch-icon-144x144 (uncompressed):
![apple-touch-icon-144x144-uncompressed](https://f.cloud.github.com/assets/5693147/2386430/00e7ac24-a92c-11e3-8070-a62cff3de60a.png)

master:
![master](https://f.cloud.github.com/assets/5693147/2386431/00e865ba-a92c-11e3-981f-f87e1a1265ff.png)

**Comment by phbernard** [comment] 2014-03-11 15:18
Thank you for the feedback. Ok, I think I understand.

RealFaviconGenerator relies on PNGQuant to compress the pictures, just like TinyPNG. TinyPNG reports the very same error you mention:

> Important notice to Mavericks users: Due to a bug in OS X 10.9 (Mavericks) compressed images may look faded when viewed in Preview or Finder. This bug has been fixed in 10.9.2. The images themselves are unaffected and will appear fine in browsers, mobile games and other applications in all versions of OS X.

This matches what you observe: lighter pictures with Mac Previewer (although your Mac version does not match TinyPNG's comment) but no issue with browsers.

Although this bug is annoying when working with PNGQuant and Mac, this is not a problem for RealFaviconGenerator: only the browsers matter. Well, except when the web dev/designer checks the pictures... with his Mac.

If that sounds correct to you, I suggest you to close the issue.

**Comment by phbernard** [comment] 2014-04-07 21:43
I think this issue can be closed.

**Closed as completed by phbernard** 2014-04-07 21:43 UTC
Labels: bug
