### ISSUE TITLE
Firefox and ICO format

### ISSUE THREAD

**Issue by J80dyc** [RealFaviconGenerator/realfavicongenerator#503] opened 2024-10-10 10:40 UTC
Using the updated generator and all is good except in Firefox on WIndows/Mac.

Firefox is fine when browsing website pages and shows the favicon but as soon as a file is opened on the site, the file opens in the browser with no favicon displaying. It seems Firefox is looking for a 48x48px icon in the .ico file but that file size is not present so the favicon doesn't render. 

When we use the checker after generating the favicon file/code it says the 48x48 png has been created but it's missing from the .ico file.

Is this a bug?

<img width="874" alt="Screenshot 2024-10-10 at 11 38 27" src="https://github.com/user-attachments/assets/398589d3-80ad-4c0e-aac7-b283603c4f57">

<img width="1150" alt="Screenshot 2024-10-10 at 11 41 41" src="https://github.com/user-attachments/assets/5293d041-dbdf-4a5d-b457-1d692f286861">

**Comment by phbernard** [comment] 2024-10-13 18:48
The ICO file does contain a 48x48 icon (in addition to 16x16 and 32x32).

The issue might be from the ICO file format itself. When I visit https://bitcoin.org/bitcoin.pdf, I can see a favicon (which is 16x16, Firefox doesn't seem to bother). When I visit https://bitcoin.org/favicon.ico, Firefox opens the favicon and shows me its content. But when I visit https://realfavicongenerator.net/favicon.ico, Firefox doesn't show me the content of the icon. Unlike Chrome, which can deals with it.

**Comment by scheinercc** [comment] 2024-10-30 01:03
Just came across the same issue.

Loading the newly generated `.ico` file from RFG, it is broken:
<img width="1674" alt="image" src="https://github.com/user-attachments/assets/b8c3eb3f-7cda-48d9-8b2e-f5bb1584e61c">
Checking the file with imagemagick
```
favicon.ico[0] ICO 48x48 48x48+0+0 8-bit sRGB 0.000u 0:00.000
favicon.ico[1] ICO 32x32 32x32+0+0 8-bit sRGB 0.000u 0:00.000
favicon.ico[2] ICO 16x16 16x16+0+0 8-bit sRGB 15086B 0.000u 0:00.000
```

I still had an old `.ico` file, which works:
<img width="1672" alt="image" src="https://github.com/user-attachments/assets/a1f0f06d-a16c-433f-9707-1edc64c4fbdb">
Imagemagick output
```
favicon.ico[0] ICO 16x16 16x16+0+0 8-bit sRGB 0.000u 0:00.000
favicon.ico[1] ICO 32x32 32x32+0+0 8-bit sRGB 0.000u 0:00.001
favicon.ico[2] ICO 48x48 48x48+0+0 8-bit sRGB 15406B 0.000u 0:00.001
```

Only difference from that little information is the packing order. Not sure if that would already throw Firefox off.

**Comment by phbernard** [comment] 2024-10-30 18:40
Thank you @scheinercc for investigating!

The reason for this particular order is that, when the order was ascending, the icon was not working... on Chrome 😭

My feeling is that there must be something wrong in https://github.com/RealFaviconGenerator/core/blob/main/packages/generate-favicon/src/icon/ico.ts . Probably "not much", so most readers can deal with the icon, somehow. Another issue with this file is that I can't find attribution, whereas I didn't write most of those lines. I didn't act as a good OSS citizen on this one 😞

**Comment by scheinercc** [comment] 2024-10-30 22:49
> when the order was ascending, the icon was not working... on Chrome

Interesting, and a bit of a pain.

**Comment by phbernard** [comment] 2024-11-23 22:18
I don't reproduce the issue. When I generate an ICO file, it is successfully opened by Firefox, whatever the order (16, 32, 48 or 48, 32, 16). @scheinercc or @J80dyc, could you provide your input image so I can get as close to the issue as possible?

**Comment by phbernard** [comment] 2024-12-10 16:28
This has been fixed in `@realfavicongenerator/generate-favicon` and RealFavicon has been redeployed. Could you give it another try to make sure the initial issue is fixed?

**Comment by J80dyc** [comment] 2024-12-11 08:58
Sorry for being absent from the replies, holidays mixed with busy schedules.
We've checked and all looks to be working perfectly.
Many thanks

**Comment by scheinercc** [comment] 2024-12-12 00:18
Works like a charm!

**Closed as completed** 2024-12-12 13:03 UTC

**Comment by peterfrompoland** [comment] 2025-09-02 23:06
I'm running into this problem, still in September 2025. If I comment out all the links generated in the html, then the favicon loads in Firefox, but if I leave them in, then it does not.

UPDATE: I found that the favicon.svg created by realfavicongenerator has width and height attributes, once I removed those, firefox rendered the svg favicon.
